### ISSUE TITLE
Add detailed instructions to install for Mac M1, please

### ISSUE THREAD

**Issue by erdeyl** [rstudio/tensorflow.rstudio.com#24]

**Comment by t-kalinowski** [comment]
Hi, thanks for filing!
I've added a [README](https://github.com/rstudio/tensorflow.rstudio.com/commit/738c51970f86823c979987745c5086aa8f81ec34) and [streamlined](https://github.com/rstudio/tensorflow.rstudio.com/commit/478389ec8d7a9958bd5cdd4f7944b799a7e77b85) the installation script. Please take a look the landing page [here](https://github.com/rstudio/tensorflow.rstudio.com) and let us know if you run into any issues 😄.

**Comment by erdeyl** [comment]
Thank you very much. After I restarted Rstudio loading the tensorflow and keras libraries and running use_condaenv("r-reticulate") everything seems to work perfect.
