### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AlphaLX** [rstudio/tensorflow.rstudio.com#55]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
argcomplete 3.0.5 requires importlib-metadata<6,>=0.23; python_version == "3.7", but you have importlib-metadata 6.3.0 which is incompatible.

The version required by the importlib-metadata package is 0.23 or 6.23? My system is Ubuntu 20.04, x86_64, could you please tell me which version I need to install?

**Comment by t-kalinowski** [comment]
You can overcome the issue by forcing an update using the `--ignore-installed` option. `py_install("tensorflow", ignore_installed=TRUE)`
