### ISSUE TITLE
virtualenv_path not found

### ISSUE THREAD

**Issue by xvtstephen** [rstudio/tensorflow.rstudio.com#61]
I have python in /usr/bin/python on linux mint 21.1 (ubuntu 22 jammy)
and when I call 
> virtualenv_create("r-reticulate", python ="/usr/bin/python/")
Error in system2(python, args, stdout = TRUE, stderr = FALSE) :

I tried to step through the function and get an error on 
> virtualenv_path(envname)
Error in virtualenv_path(envname) : 
  could not find function "virtualenv_path"
listing the reticulate namespace does not show a virtualenv_path function.
also:
$ which virtualenv
/usr/local/bin/virtualenv
> getOption("reticulate.virtualenv.module")
NULL

Please, help.
Thanks

**Comment by t-kalinowski** [comment]
Hmm, I can't reproduce locally. Perhaps something went wrong with the package installation? Can you please reinstall reticulate:
```r
install.packages("reticulate")
```

Also, why is there a trailing `/` in `/usr/bin/python/`? Should that just be `/usr/bin/python`?

**Comment by xvtstephen** [comment]
Hello,
you are correct about the slash, it should not be there. but where is
the function virtualenv_path() called in virtualenv_create()?

also should getOption("reticulate.virtualenv.module") etc find
something?

I will try the same on another box. I was able to install everything
from within Rstudio.
Cheers
Stephen

**Comment by t-kalinowski** [comment]
Both virtualenv_path and virtualenv_create are from the reticulate package.

Glad you got it working.
